const hotData = [
  {
    sid: 2,
    Name: '愛維他檸檬酸鈣固本加強錠120PC',
    categories: '保健食品',
    image: 'http://localhost:3000/images/products/products(2).jpeg',
    Location: '骨骼',
    nutrient: '維生素D、鈣、鋅、鎂、銅、錳',
    brand_company: '森宏',
    quantity: '120 PC',
    price: 2280,
    special_offer: '',
    Edible_Method: '1日/1~2錠',
    place_origin: '美國',
    EXP: '2年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
  {
    sid: 1,
    Name: '保佳兆UCII複合錠60PC',
    categories: '保健食品',
    image: 'http://localhost:3000/images/products/products(1).jpeg',
    Location: '骨骼',
    nutrient: '維生素C、維生素D、葡萄糖胺、鈣、鋅、鎂、銅、錳、膠原蛋白',
    brand_company: '保佳兆',
    quantity: '60 PC',
    price: 1428,
    special_offer: '',
    Edible_Method: '1日/1錠',
    place_origin: '美國',
    EXP: '2年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
  {
    sid: 3,
    Name: '三多 高纖乳酸菌PP粉末食品-2gx20',
    categories: '保健食品',
    image: 'http://localhost:3000/images/products/products(3).jpeg',
    Location: '腸胃',
    nutrient: '益生菌、乳酸菌、酵素、木寡糖',
    brand_company: '三多',
    quantity: '2g * 20',
    price: 375,
    special_offer: '',
    Edible_Method: '1日/2包',
    place_origin: '台灣',
    EXP: '2年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
  {
    sid: 5,
    Name: '視易適葉黃素',
    categories: '保健食品',
    image: 'http://localhost:3000/images/products/products(5).jpeg',
    Location: '眼睛',
    nutrient: '蝦紅素、花青素、葉黃素、山桑子、亞麻仁油、維生素E、Omega3',
    brand_company: '大研生醫',
    quantity: '30PC',
    price: 1899,
    special_offer: '1599',
    Edible_Method: '1日/1粒',
    place_origin: '台灣',
    EXP: '2年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
  {
    sid: 19,
    Name: '三多金盞花葉黃素複方-100PC粒',
    categories: '保健食品',
    image: 'http://localhost:3000/images/products/products(19).jpeg',
    Location: '眼睛',
    nutrient:
      '葉黃素酯30mg、玉米黃素酯1.2mg、魚油、鋅、硒、維生素A、維生素C、維生素E',
    brand_company: '三多',
    quantity: '100 PC',
    price: 350,
    special_offer: '290',
    Edible_Method: '1日/1粒',
    place_origin: '台灣',
    EXP: '2年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
]

export { hotData }
