const hotData = [
  {
    sid: 33,
    Name: 'Now Foods, 葉黃素，雙重強度',
    categories: '保健食品',
    image: 'http://localhost:3000/images/products/products(32).jpeg',
    Location: '眼睛',
    nutrient:
      '葉黃素、纖維素（膠囊）、硬脂酸（植物源）、甜菜粉、抗壞血酸棕櫚酸酯',
    brand_company: 'Now Foods',
    quantity: '90 PC',
    price: 489,
    special_offer: '',
    Edible_Method: '1日/1粒',
    place_origin: '美國',
    EXP: '2年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
  {
    sid: 38,
    Name: '益植酵【睡著酵代謝夜酵素】',
    categories: '保健食品',
    image: 'http://localhost:3000/images/products/products(37).jpeg',
    Location: '睡眠',
    nutrient:
      '枳椇子萃取物、氧化鎂、濃縮乳清蛋白(含18種胺基酸)、維生素C、綜合消化酵素(木瓜酵素、蛋白酵素、脂肪分解酵素',
    brand_company: '易珈',
    quantity: '30 PC',
    price: 430,
    special_offer: '',
    Edible_Method: '1日/1粒',
    place_origin: '台灣',
    EXP: '2年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
  {
    sid: 21,
    Name: '綜合鈣+D3粉包-完美鈣鎂比例2:1(24包/盒)',
    categories: '保健食品',
    image: 'http://localhost:3000/images/products/products(21).jpeg',
    Location: '骨骼',
    nutrient: '檸檬酸鈣、麥芽糊精、紅藻粉、蔗糖、檸檬果汁粉、氧化鎂、赤藻糖醇',
    brand_company: '大研生醫',
    quantity: '2g * 24',
    price: 520,
    special_offer: '',
    Edible_Method: '1日/1包',
    place_origin: '台灣',
    EXP: '3年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
  {
    sid: 72,
    Name: '《白博士》抗菌洗手乳-500ml',
    categories: '生活用品',
    image: 'http://localhost:3000/images/products/products(71).jpeg',
    Location: '手部',
    nutrient:
      '聚季銨鹽-7、聚山梨醇酯80、Antiseptic、Chlorhexidine gluconate、烷基聚葡萄糖苷',
    brand_company: '白博士',
    quantity: '500ml',
    price: 75,
    special_offer: '',
    Edible_Method: '詳見包裝',
    place_origin: '台灣',
    EXP: '5年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T02:05:24.000Z',
  },
  {
    sid: 53,
    Name: '克司博 75%酒精液 (500ml/瓶)乙類成藥',
    categories: '生活用品',
    image: 'http://localhost:3000/images/products/products(52).jpeg',
    Location: '皮膚',
    nutrient: 'ALCOHOL 95% ( EQ TO ETHANOL 95%)',
    brand_company: '醫強科技',
    quantity: '500ml',
    price: 80,
    special_offer: '',
    Edible_Method: '詳見包裝',
    place_origin: '台灣',
    EXP: '5年',
    MFD: '詳見包裝',
    create_at: '2021-08-05T01:10:10.000Z',
  },
]

export { hotData }
